# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "test" do |test|
    test.vm.box = "debian/buster64"
    test.vm.hostname = "test"

    # Configuration réseau
    test.vm.network "private_network", ip: "192.168.10.2"

    # Configuration des provisions
    test.vm.provision "shell", inline: <<-SHELL
      # Vous pouvez ajouter ici les tests que vous souhaitez effectuer
      # Par exemple, vérifier l'accès aux pages web et tester des attaques classiques
    SHELL
  end
end

